name: MaceLimiter
version: 1.0.0
main: com.nobowl.macelimiter.MaceLimiter
api-version: 1.20
authors: [NoBowl]
description: "Limit the number of maces in the world. Professional-grade plugin by NoBowl."

commands:
  macelimiter:
    description: Admin commands for MaceLimiter
    usage: /<command>
    permission: macelimiter.admin

permissions:
  macelimiter.admin:
    description: Allows access to all MaceLimiter admin commands
    default: op
  macelimiter.bypass:
    description: Allows bypassing the mace limit
    default: false
